apiVersion: managed.openshift.io/v1alpha1
kind: SubjectPermission
metadata:
  name: dedicated-admins
  namespace: openshift-rbac-permissions
spec:
  subjectKind: Group
  subjectName: dedicated-admins
  clusterPermissions:
    - dedicated-admins-cluster
  permissions:
    - 
      clusterRoleName: dedicated-admins-project
      namespacesAllowedRegex: ".*"
                              # (?!openshift-operators(-redhat)?) - do not deny openshift-operators and openshift-operators-redhat
                              # (kube|kube-.*|openshift|openshift-.*|default|redhat-.*) - deny system namespaces
      namespacesDeniedRegex: "^(?!openshift-operators(-redhat)?)(kube|kube-.*|openshift|openshift-.*|default|redhat-.*)$"
      allowFirst: true
    - 
      clusterRoleName: admin 
      namespacesAllowedRegex: ".*" 
                              # (?!openshift-operators(-redhat)?) - do not deny openshift-operators and openshift-operators-redhat
                              # (kube|kube-.*|openshift|openshift-.*|default|redhat-.*) - deny system namespaces
      namespacesDeniedRegex: "^(?!openshift-operators(-redhat)?)(kube|kube-.*|openshift|openshift-.*|default|redhat-.*)$"
      allowFirst: true
